spring:
  config:
    import:
      - classpath:application-common-${spring.profiles.active:default}.properties
      - classpath:auth-service/application-auth-${spring.profiles.active:default}.properties

