spring:
  config:
    import:
      - classpath:config/application-common-${spring.profiles.active:default}.properties
      - classpath:config/analytics-service/application-analytics-${spring.profiles.active:default}.properties

