spring:
  config:
    import:
      - classpath:config/application-common-${spring.profiles.active:default}.properties
      - classpath:config/user-details-service/application-user-details-${spring.profiles.active:default}.properties

