spring:
  config:
    import:
      - classpath:config/application-common-${spring.profiles.active:default}.properties
      - classpath:config/auth-service/application-auth-${spring.profiles.active:default}.properties

