spring:
  config:
    import:
      - classpath:application-common-${spring.profiles.active:default}.properties
      - classpath:user-details-service/application-user-details-${spring.profiles.active:default}.properties

